CustomerToolKitMVP/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('result', views.result, name='result'),
    path('download', views.download_packet, name='download'),
]

categories/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=100)
    description = models.TextField()


    def __str__(self):
        return self.name

custom_user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _

from .managers import CustomUserManager

# Create your models here.

class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = CustomUserManager()

    def __str__(self):
        return self.email

pages/models.py
from django.db import models

# Create your models here.

turf/models.py
from django.db import models

from categories.models import Category
# Create your models here.

class TurfType(models.Model):
    name = models.CharField(max_length=255)
    pile_height = models.DecimalField(decimal_places=2, max_digits=4)
    blade_shape = models.CharField(max_length=50)
    blade_material = models.CharField(max_length=50)
    tuft_bind_strength = models.IntegerField()
    backing_material = models.CharField(max_length=50)
    warranty_length = models.IntegerField()
    spec_sheet_url = models.URLField(max_length=255)
    pet_friendly = models.BooleanField()
    sports_field = models.BooleanField()
    category = models.ManyToManyField(Category)

    def __str__(self):
        return self.name

custom_user/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('email',)


class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = CustomUser
        fields = ('email',)

categories/views.py
from django.shortcuts import render

# Create your views here.

custom_user/views.py
from django.shortcuts import render

# Create your views here.

pages/views.py
import os.path

from django.http import HttpResponseBadRequest, HttpResponseNotAllowed, HttpResponse, HttpResponseServerError
from django.shortcuts import render
from django.conf import settings

from turf.models import *
from .utils import pdf_generator

# Create your views here.

def index(request):
    """
    Simple view that shows form for selecitng the type of turf to show user

    :param request:
    :return:
    """
    return render(request, 'pages/index.html')

def result(request):
    """
    Handles results from the search feature on the homepage
    Calls pdf_generator to generate the pdf packet

    :param request: request from browser
    :return:
    """
    if request.method == 'POST':
        form_data = request.POST.dict()
        session_key = request.session.session_key
    else:
        return HttpResponseNotAllowed

    if not form_data.get('userCategory'):
        return HttpResponseBadRequest




    if form_data.get("petFriendly"):
        results = TurfType.objects.filter(category__name=form_data.get('userCategory')).exclude(pet_friendly=False)[:3]
    elif form_data.get("sportsField"):
        results = TurfType.objects.filter(category__name=form_data.get('userCategory')).exclude(sports_field=False)[:3]
    else:
        results = TurfType.objects.filter(category__name=form_data.get('userCategory'))[:3]

    context = {"results": results}

    if not pdf_generator(request, results, session_key):
        return HttpResponseServerError

    return render(request, 'pages/results.html', context)


def download_packet(request):
    """
    Pulls session key from browser cookies and uses that to find the right packet to give to the user.
    Then downloads the packet for the user.
    """


    session_key = request.session.session_key
    packet_path = os.path.join(settings.BASE_DIR, "media", f"packet_{session_key}.pdf")

    with open(packet_path, "rb") as f:
        response = HttpResponse(f, content_type="application/pdf")
        response['Content-Disposition'] = 'attachment; filename="packet.pdf"'
    return response

turf/views.py
from django.shortcuts import render

# Create your views here.

templates/pages/comparison.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Turf Comparison</title>
    <style>
        @page {
            size: letter landscape;
            margin: 20mm;
        }

        body {
            font-family: sans-serif;
            margin: 20mm;
        }

      .container {
            width: 100%;
            display: block;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #222; /* Dark background for header */
            color: #DAA520; /* Gold text color for header */
        }

        tbody tr:nth-child(odd) {
            background-color: #f0fff0; /* Light green for odd rows */
        }

        tbody tr:nth-child(even) {
            background-color: #f5fff5; /* Slightly lighter green for even rows */
        }

        h2 {
            text-align: center;
            margin-bottom: 10px;
            color: #006400; /* Dark green for heading */
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>Turf Comparison</h2>
        <table>
            <thead>
                <tr>
                    <th></th>
                    {% for turf in results %}
                    <th>{{ turf.name }}</th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Blade Shape</td>
                    {% for turf in results %}
                    <td>{{ turf.blade_shape }}</td>
                    {% endfor %}
                </tr>
                <tr>
                    <td>Blade Material</td>
                    {% for turf in results %}
                    <td>{{ turf.blade_material }}</td>
                    {% endfor %}
                </tr>
                <tr>
                    <td>Backing Material</td>
                    {% for turf in results %}
                    <td>{{ turf.backing_material }}</td>
                    {% endfor %}
                </tr>
                <tr>
                    <td>Pile Height</td>
                    {% for turf in results %}
                    <td>{{ turf.pile_height }}</td>
                    {% endfor %}
                </tr>
            </tbody>
        </table>
    </div>
</body>
</html>

templates/pages/cover.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Turf Report Cover Page</title>
    <style>
        @page {
            size: letter; /* Set page size explicitly to letter */
            margin: 25mm;  /* Adjust margins as needed */
        }

        body {
            font-family: sans-serif;
            text-align: center;
            background-color: #f0fff0; 
            color: #006400; 
        }

        h1 {
            font-size: 3em;
            margin-bottom: 1em;
            /* No need for overflow and text-overflow anymore */
        }

      .container {
            margin-top: 30%; 
        }

        p {
            line-height: 1.6;
            color: #222;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Your Personal Turf Report</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.</p>
        <p>Proin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. Duis semper. Duis arcu massa, scelerisque vitae, consequat in, pretium a, enim. Pellentesque congue. Ut in risus volutpat libero pharetra tempor. Cras vestibulum bibendum augue. Praesent egestas leo in pede. Praesent blandit odio eu enim. Pellentesque sed dui ut augue blandit sodales

templates/pages/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Customer Kit</title>
</head>
<body>
    <form id="turfForm" method="post" action="{% url 'pages:result' %}">
        {% csrf_token %}
        <label for="userCategory">I am a: </label>
        <select id="userCategory" name="userCategory">
            <option value="">Select an option</option>
            <option value="Homeowner">Homeowner</option>
            <option value="HomeownersAssociation">HOA</option>
            <option value="PropertyManager">Property Manager</option>
            <option value="Builder">Builder</option>
            <option value="Municipality">Municipality</option>
        </select>
        
        <div id="modifierContainer" style="display: none">
            <label for="modifierQuestion" id="modifierQuestionLabel">I am looking for pet friendly turf</label>
            <input type="checkbox" id="modifierQuestion" name="petFriendly">
        </div>
        
        <button type="submit">Submit</button>
    </form>
</body>
<script>
    const userCategory = document.getElementById("userCategory")
    const modifierContainer = document.getElementById("modifierContainer")
    const modifierQuestion = document.getElementById("modifierQuestion")
    const modifierQuestionLabel = document.getElementById("modifierQuestionLabel")
    
    userCategory.addEventListener('change', () => {
            console.log(userCategory.value)
            modifierContainer.style.display = "block"

            if (userCategory.value === 'homeowner' ||
                userCategory.value === 'hoa' ||
                userCategory.value === 'propertyManager') {
                modifierQuestionLabel.textContent = "I am looking for Pet Friendly Turf"
                modifierQuestion.name = "petFriendly"
            } else if (
                userCategory.value === 'Builder' ||
                userCategory.value === 'Municipality') {
                modifierQuestionLabel.textContent = "I am looking for Sports Field Turf"
                modifierQuestion.name = "sportsField"
            }
        }
    )
    
    
</script>

</html>

templates/pages/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Results</title>
</head>
<body>
    {% csrf_token %}
    {% for turf in results %}
        <span>{{ turf.name }}</span> <br>
    {% endfor %}

    <button><a href="{% url 'pages:download' %}">Download Packet</a></button>

</body>
</html>